/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TiSuporteRouteImport } from './routes/ti-suporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TiSuporteRoute = TiSuporteRouteImport.update({
  id: '/ti-suporte',
  path: '/ti-suporte',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/canais': typeof CanaisRoute
  '/mensagens': typeof MensagensRoute
  '/modelos': typeof ModelosRoute
  '/onboarding': typeof OnboardingRoute
  '/ti-suporte': typeof TiSuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/canais': typeof CanaisRoute
  '/mensagens': typeof MensagensRoute
  '/modelos': typeof ModelosRoute
  '/onboarding': typeof OnboardingRoute
  '/ti-suporte': typeof TiSuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/canais': typeof CanaisRoute
  '/mensagens': typeof MensagensRoute
  '/modelos': typeof ModelosRoute
  '/onboarding': typeof OnboardingRoute
  '/ti-suporte': typeof TiSuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/canais'
    | '/mensagens'
    | '/modelos'
    | '/onboarding'
    | '/ti-suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/canais'
    | '/mensagens'
    | '/modelos'
    | '/onboarding'
    | '/ti-suporte'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/canais'
    | '/mensagens'
    | '/modelos'
    | '/onboarding'
    | '/ti-suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CanaisRoute: typeof CanaisRoute
  MensagensRoute: typeof MensagensRoute
  ModelosRoute: typeof ModelosRoute
  OnboardingRoute: typeof OnboardingRoute
  TiSuporteRoute: typeof TiSuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ti-suporte': {
      id: '/ti-suporte'
      path: '/ti-suporte'
      fullPath: '/ti-suporte'
      preLoaderRoute: typeof TiSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CanaisRoute: CanaisRoute,
  MensagensRoute: MensagensRoute,
  ModelosRoute: ModelosRoute,
  OnboardingRoute: OnboardingRoute,
  TiSuporteRoute: TiSuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
